### ISSUE TITLE
writing cfradial changes attributes to strings, matlab cannot read this

### ISSUE THREAD

**Issue by nphoban** [ARM-DOE/pyart#487] opened 2016-02-17 20:59 UTC
I am attempting to read in a cfradial file, dealias the velocities, and output a new cfradial file with the added dealiased velocity field. Along the way, the attributes of the existing data become changed to a "string" format. This string format is not compatible with matlab and I need it to be. The added dealiased velocity field is outputted correctly, but all the other fields are changed. I have attached a picture of my cfradial file before and after the processing. 

I believe this issue might be from line 700 in cfradial.py. Here data that is type 'U' is assigned data type 'S'. 
![beforepythonprocessing](https://cloud.githubusercontent.com/assets/17302254/13124526/eabb3588-d58e-11e5-90a4-55974679ee9d.PNG)
![afterpythonprocessing](https://cloud.githubusercontent.com/assets/17302254/13124538/fb910112-d58e-11e5-9f18-6eb71dc590d8.PNG)

**Comment by jjhelmus** [comment] 2016-02-17 23:20
@nphoban Can you provide a bit more details on this issue?  I can't see from the screenshots posted what variables are changing.  

One though is that by default the `pyart.io.write_cfradial` function creates netCDF4 version 4 files which may not be able to be read in Matlab.  If you set the **format** parameter to 'NETCDF3_CLASSIC' then the function will create a netCDF version 3 files.

**Comment by scollis** [comment] 2016-02-17 23:32
Is it that it is now writing strings rather than an array of Chars?

**Comment by nphoban** [comment] 2016-02-18 15:28
@jjhelmus Matlab can read netCDF4 and I have also tried writing netCDF3 using 'NETCDF3_CLASSIC' and that did not fix the problem. 

In the images, if you look below the float variables you will see the word string is now added in front of most of the variables attributes. It appears the actual data in the variables is fine, but the attributes have changed to a format that matlab cannot read. Except for the added variable dealiased_velocity where the attributes and data are written correctly.

**Comment by jjhelmus** [comment] 2016-02-18 15:39
I understand the issue now, thanks for clarifying.  I was looking at the wrong information in the images, sorry about that.  I'm not sure what exactly is causing this but I will look into it and get back when I have an answer.

**Comment by jjhelmus** [comment] 2016-02-18 21:21
From the testing I've done, this conversion of text/byte attribute to string attributes seems to be caused by a recent update to the netcdf4-python library.  You may be able to work around this issue by installing an older version of netcdf4 which does not write out string attributes.  Version 1.1.1 should work and can be installed using `conda install netcdf4==1.1.1` if you are using Python.

I've filed an issue with the netcdf4-python library (Unidata/netcdf4-python#529) to see if they have any recommendation on how to deal with this issue.

**Comment by jjhelmus** [comment] 2016-02-18 22:10
xarray seems to be discussing how to deal with the same issue, pydata/xarray#681

**Comment by jjhelmus** [comment] 2016-02-22 14:33
I'm still working with the netcdf4-python developers on a good solution to this issue.  For the time being my suggestion would be to use an older version of the netcdf4-python library if you need to create NetCDF file with Py-ART that can be read in Matlab.

**Comment by nphoban** [comment] 2016-02-22 14:41
Thank you for your help.

**Comment by jjhelmus** [comment] 2016-08-17 14:46
I believe this issue has been address in changes to netcdf4-python in the linked issue, closing.

If you are still running into this issue @nphoban or anyone else feel re-open this issue.

**Closed by jjhelmus** 2016-08-17 14:46 UTC
Labels: component: pyart.io, Defect
