### ISSUE TITLE
grid_from_radars issue with odim data

### ISSUE THREAD

**Issue by joshuass** [ARM-DOE/pyart#530] opened 2016-05-10 23:46 UTC
Hi pyART team,

The regridding function grid_from_radars is producing a strange spiral pattern for odimh5 files, see the following [notebook](https://github.com/uq-crg/rapic_to_pyart/blob/master/20151126_MtIsa_dust_storm.ipynb))
[odimh5 file](https://www.dropbox.com/s/k3w39pzwbm8hius/201511261318Mnt_Isa.h5?dl=0)

CAPPI image of the scan: 
![idr75_20151126_1318_128](https://cloud.githubusercontent.com/assets/16043083/15165910/0572c426-175d-11e6-91f5-8b9ed5f3324c.png)

The odimh5 data file processes fine in matlab, so I'm not sure what's going on.

Joshua

**Comment by joshuass** [comment] 2016-05-11 00:20
I had a quick attempt at plotting RHIs from the Mt Isa dataset and it looks like the problem may reside in the odimh5 reader (same with #484 and #445). Volume derived RHI scans look very odd, it appears the read has mixed up the azimuth and elevation coordinates of the radar gates!
See the following [notebook](https://github.com/uq-crg/rapic_to_pyart/blob/master/20151126_MtIsa_dust_storm2.ipynb)

**Comment by jjhelmus** [comment] 2016-05-11 00:39
@joshuass Could you repost the link to the original notebook and the sample file.  The first seems to be a link to localhost and send second is 404 for me.

**Comment by jjhelmus** [comment] 2016-05-11 00:42
PR #524 added support for reading ODIM H5 containing RHIs but it was really a stab in the dark.  I have yet to find a ODIM H5 ELEV file that is close enough to the standards to test against.

**Comment by joshuass** [comment] 2016-05-11 05:17
Sorry about that, I've fixed the links. The odimh5 file above contains VOL object.
Great to hear you've added RHI support, I'll test it soon.

**Comment by jjhelmus** [comment] 2016-05-11 13:18
Looking at the individual sweeps in the file it looks like each sweep successive sweep is rotated ~45 degree.  Let me dig into this more it a bit to see if the issue is in the file or in how Py-ART is reading it in.

**Comment by jjhelmus** [comment] 2016-05-11 15:58
Okay, so in ODIM H5 files when a sweep's azimuth angles are not explicitly given in the `startazA` and `stopazA` attributes then as per section 5.1 of the standards doc (version 2.2) the polar data should be ordered starting at 0 degrees and proceed clockwise.  The **index** of the first ray collected in time is given by the `a1gate` attribute in the dataset's where group.  I had misread the meaning of the `a1gate` attribute, using it as the first azimuth angle, which is leading to the rotation issue.  I'll have a fix for this and a few Python 3 related ODIM issues shortly.

**Comment by jjhelmus** [comment] 2016-05-11 17:32
With the fixes in PR #531 the gridding seems to be reasonable.

``` Python 
import pyart
import matplotlib.pyplot as plt
import numpy as np

fn = '201511261318Mnt_Isa.h5'
radar = pyart.aux_io.read_odim_h5(fn, file_field_names=True)
grids = pyart.map.grid_from_radars(
    radar, grid_shape=(31, 301, 301),
    grid_limits=((0, 15000.0),(-150000, 150000), (-150000, 150000)),
    fields=['DBZH'], gridding_algo="map_gates_to_grid")

plt.imshow(grids.fields['DBZH']['data'][0], origin='lower')
plt.savefig('figure1.png')

plt.figure()
display = pyart.graph.GridMapDisplay(grids)
display.plot_grid('DBZH', level=3, vmin=-8, vmax=64, cmap='pyart_NWSRef')
plt.savefig('figure2.png')
```

![figure1](https://cloud.githubusercontent.com/assets/1050278/15190221/5784060a-1774-11e6-931a-4aef4303509c.png)
![figure2](https://cloud.githubusercontent.com/assets/1050278/15190224/58d1c1be-1774-11e6-9f90-7bf4d138ab68.png)

**Closed** 2016-05-11 17:37 UTC

**Comment by jjhelmus** [comment] 2016-05-11 17:39
@joshuass Feel free to re-open this issue if the fix does not work for you.

**Comment by joshuass** [comment] 2016-05-12 04:04
Hi Jonathan,

It's working perfectly now. Thanks for the fix!
https://github.com/uq-crg/rapic_to_pyart/blob/master/20151126_MtIsa_dust_storm_nointerp.ipynb

Cheers,
Joshua
